# Generated by Django 3.1.3 on 2022-01-29 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_produit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
        migrations.CreateModel(
            name='Produit_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.produit')),
            ],
        ),
    ]
